# Generated by Django 3.0.5 on 2021-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration', models.IntegerField()),
                ('campus', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('situation', models.CharField(max_length=200)),
            ],
        ),
    ]
